<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Can corpus distributions predict clause selection? – Statistical Methods in Linguistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../missing-data/index.html" rel="next">
<link href="../factorization/choosing-components.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9c7dc7b1de60a33592ad3037cf4676f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-da6d1b1257fb39ecc86e2a03663c2683.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../factorization/index.html">Factorization</a></li><li class="breadcrumb-item"><a href="../factorization/valex-megaacceptability.html">Can corpus distributions predict clause selection?</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Statistical Methods in Linguistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../learning-path.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter dependencies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decks/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course slides</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignments</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Released problem sets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problem-sets/ps1/ps1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PS1: Paired acoustic measurements</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problem-sets/ps2/ps2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PS2: Prediction across passages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problem-sets/ps3/ps3-dative-alternation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PS3: Dative alternation and logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problem-sets/ps4/ps4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PS4: Commitment in discourse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problem-sets/ps5/ps5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PS5: Structure in phoneme inventories</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Data and probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From linguistic records to probabilities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/linguistic-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Turning linguistic records into data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/making-sense-of-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Turning a question into a comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/zipfs-law.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A first pattern: Zipf’s law</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Probability spaces</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/possibilities-and-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sample spaces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/event-spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sigma-algebras</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/generating-event-spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generating a sigma-algebra</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/probability-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability measures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/probability-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mutually exclusive events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/joint-probability-of-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Joint probability of events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/conditional-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/probability-factorization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The product rule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/bayes-rule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayes’ rule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Independence</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Random variables and distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From outcomes to distributions</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Random variables</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/why-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Why use random variables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/defining-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Defining random variables</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Discrete and continuous variables</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/discrete-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Discrete random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/probability-mass-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability mass functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/continuous-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/probability-density-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability density functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/cumulative-distribution-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cumulative distribution functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/expected-values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Expected values</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/expectation-of-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Expectations of functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/linearity-of-expectation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linearity of expectation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/when-expectations-fail.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">When an expectation does not exist</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/variance-and-covariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/standard-deviation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standard deviation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/central-moments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Central moments</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Discrete distributions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/bernoulli-and-categorical-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The categorical distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/bernoulli-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Bernoulli distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/binomial-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The binomial distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/hypergeometric-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The hypergeometric distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/geometric-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The geometric distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/negative-binomial-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The negative binomial distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/poisson-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Poisson distribution</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Continuous distributions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/uniform-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The uniform distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/beta-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The beta distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/student-t-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Student’s t distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/chi-squared-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The chi-squared distribution</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Simulation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/inverse-transform-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling with cumulative probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/random-seeds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducing a simulation</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Joint distributions and summaries</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/joint-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Joint distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/marginal-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Marginal distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/conditional-independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/conditional-expectation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional expectation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/covariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../random-variables-and-distributions/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning from a sample</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Frequentist inference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/populations-and-samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Populations and samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/independent-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Independent sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/pronoun-case-example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A corpus proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/maximum-likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Maximum likelihood</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/poisson-maximum-likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Maximum likelihood for a Poisson mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/properties-of-estimators.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/standard-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/estimator-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estimator bias</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/mean-squared-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mean squared error</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/exact-binomial-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exact intervals for a binomial probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/bootstrap-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrap confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/null-hypotheses-and-test-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Null hypotheses and test statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/one-sample-t-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference for one mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/paired-observations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paired observations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/paired-mean-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference for a paired mean difference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/independent-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing two independent means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/fishers-exact-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fisher’s exact test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/chi-squared-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The chi-squared test of independence</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Bayesian inference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/posterior-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Posterior distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/posterior-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing posterior draws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/conjugate-priors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conjugate priors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/prior-predictive-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prior predictive distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/predictive-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Posterior predictive distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/beyond-conjugacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">When the posterior will not normalize by hand</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Posterior computation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/monte-carlo-integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Monte Carlo integration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/importance-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importance sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/markov-chains.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Markov chains</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/markov-chain-monte-carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Markov chain Monte Carlo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/metropolis-hastings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Metropolis-Hastings sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/hamiltonian-monte-carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hamiltonian Monte Carlo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/mass-matrix-geometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mass matrices and posterior geometry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/no-u-turn-sampler.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The No-U-Turn Sampler</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Implementing a model in Stan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/checking-markov-chains.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading trace plots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/rhat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-chain agreement</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/autocorrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Autocorrelation in a Markov chain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/effective-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Effective sample size</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/divergent-transitions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Divergent Hamiltonian transitions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/parameter-pair-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading pairs plots of posterior draws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/generated-quantities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generating derived quantities in Stan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistical-inference/posterior-predictive-checks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Posterior predictive checks</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression as a sequence of extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/regression-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/simple-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A straight-line mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/centering-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Centering a predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/response-transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transforming a response</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/frequentist-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting a linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/linear-regression-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Uncertainty in a fitted slope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/coefficient-of-determination.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The coefficient of determination</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Residuals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/checking-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Checking a linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/leverage-and-influence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Leverage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/influence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Influence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/bayesian-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayesian linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Adding a second predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/design-matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Design matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/coding-categorical-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Coding a categorical predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/sum-coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sum coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/helmert-coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Helmert coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/inverse-helmert-coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Earlier-versus-later Helmert contrasts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interaction terms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/correlated-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlated predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/variance-inflation-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variance inflation from correlated predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/ridge-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Shrinking correlated coefficients</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/residualizing-a-predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Residualizing a predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/heteroscedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Changing conditional variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/distributional-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling conditional scale</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="true">
 <span class="menu-text">Model criticism and prediction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicting observations the model did not see</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/prediction-targets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What must be new at prediction time</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/predictive-loss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predictive loss</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/bias-variance-tradeoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prediction bias and prediction variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/training-and-test-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training and test data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/cross-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/leave-one-out-cross-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Leaving out one unit at a time</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/grouped-cross-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grouped cross-validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/comparing-predictive-loss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing predictive loss</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/likelihood-ratio-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing nested likelihoods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/information-criteria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Penalizing in-sample fit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/psis-loo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pareto-smoothed importance sampling leave-one-out cross-validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-criticism-and-prediction/waic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The widely applicable information criterion</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="true">
 <span class="menu-text">Generalized linear models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/why-generalized-linear-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">When ordinary linear regression cannot model the response</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/link-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Link functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/generalized-linear-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Components of a generalized linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/exponential-family.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The exponential family</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/sufficient-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sufficient statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/iteratively-reweighted-least-squares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Iteratively reweighted least squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/deviance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deviance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/odds-and-log-odds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From probabilities to log odds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/logistic-regression-example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Verb type and temporal preposition choice</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/logistic-regression-with-multiple-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two predictors in logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/deviance-residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deviance residuals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/ordinal-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ordinal regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/poisson-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Poisson regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/exposure-offsets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exposure offsets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/poisson-regression-example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Poisson regression for linguistic diversity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/count-overdispersion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Checking Poisson dispersion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/quasi-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quasi Poisson variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/zero-inflated-counts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zero-inflated counts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/negative-binomial-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Negative binomial regression</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Bounded responses</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/bounded-responses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bounded responses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/why-not-beta-sliders.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Why standard beta regression fails for sliders</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/ordered-beta-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ordered-beta regression</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="true">
 <span class="menu-text">Mixed effects models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/structured-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repeated units in linguistic data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/fixed-and-random-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Population comparisons and sampled variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/random-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random effects and partial pooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/random-intercepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random intercept models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/intraclass-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intraclass correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/random-effect-estimates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Group-specific estimates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/random-slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random slope models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/random-effect-correlations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlations among random effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/singular-fits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Singular mixed model fits</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/generalized-linear-mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generalized linear mixed models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/ordinal-mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ordinal mixed models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/aspectual-similarity-example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bounded similarity judgments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/laplace-approximation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Laplace approximation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/poisson-mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Poisson mixed-effects models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression-models/overdispersion-and-random-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Group heterogeneity and marginal dispersion</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="true">
 <span class="menu-text">Experimental design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimental design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/units-of-assignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Units of assignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/random-assignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random assignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/within-participant-designs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Within-participant designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/between-participant-designs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Between-participant designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/counterbalancing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Counterbalancing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/exclusion-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exclusion rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../experimental-design/power-by-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Power by simulation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="true">
 <span class="menu-text">Latent structure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Finding unobserved groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/representing-objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Representing objects for clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/distance-and-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distance and scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/k-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">K-means clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/within-cluster-loss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Within-cluster loss</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/silhouette-scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Silhouette widths</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/unsupervised-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Validation without outcome labels</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/gaussian-mixtures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gaussian mixtures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/posterior-membership.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Posterior membership</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/expectation-maximization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Expectation-maximization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/choosing-a-mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Choosing a mixture with BIC</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../latent-structure/validating-a-mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Validating a mixture on held-out speakers</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" role="navigation" aria-expanded="true">
 <span class="menu-text">Factorization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-22" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Factorization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/data-matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linguistic data matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/centering-and-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Centering and scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/rank-one-structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rank one structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/singular-value-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Singular value decomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/principal-component-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Principal component analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/scores-and-loadings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scores and loadings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/reconstruction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reconstruction from components</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/choosing-components.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Choosing the number of components</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../factorization/valex-megaacceptability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Can corpus distributions predict clause selection?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" role="navigation" aria-expanded="true">
 <span class="menu-text">Missing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-23" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../missing-data/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Missing data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../missing-data/missingness-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Missingness patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../missing-data/missingness-mechanisms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Missingness mechanisms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../missing-data/complete-case-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Complete case analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../missing-data/pca-imputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Iterative PCA imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../missing-data/validating-imputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Validating an imputation procedure</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" role="navigation" aria-expanded="true">
 <span class="menu-text">Custom model design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-24" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Custom model design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/annotations-as-measurements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Annotations are measurements</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/generative-stories.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data-generating processes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/writing-a-joint-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writing a joint model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/annotator-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Annotator effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/gated-annotations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gated annotations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/parameter-recovery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameter recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../custom-models/uds-measurement-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Measuring natural parts judgments</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#start-with-the-linguistic-observations" id="toc-start-with-the-linguistic-observations" class="nav-link active" data-scroll-target="#start-with-the-linguistic-observations">Start with the linguistic observations</a></li>
  <li><a href="#interpret-the-normalized-response-scale" id="toc-interpret-the-normalized-response-scale" class="nav-link" data-scroll-target="#interpret-the-normalized-response-scale">Interpret the normalized response scale</a></li>
  <li><a href="#construct-the-corpus-predictor" id="toc-construct-the-corpus-predictor" class="nav-link" data-scroll-target="#construct-the-corpus-predictor">Construct the corpus predictor</a></li>
  <li><a href="#state-the-two-hypotheses" id="toc-state-the-two-hypotheses" class="nav-link" data-scroll-target="#state-the-two-hypotheses">State the two hypotheses</a></li>
  <li><a href="#change-only-the-predictor-representation" id="toc-change-only-the-predictor-representation" class="nav-link" data-scroll-target="#change-only-the-predictor-representation">Change only the predictor representation</a></li>
  <li><a href="#keep-every-fitted-choice-inside-the-training-data" id="toc-keep-every-fitted-choice-inside-the-training-data" class="nav-link" data-scroll-target="#keep-every-fitted-choice-inside-the-training-data">Keep every fitted choice inside the training data</a></li>
  <li><a href="#define-the-predictive-score" id="toc-define-the-predictive-score" class="nav-link" data-scroll-target="#define-the-predictive-score">Define the predictive score</a></li>
  <li><a href="#evaluate-the-hypotheses" id="toc-evaluate-the-hypotheses" class="nav-link" data-scroll-target="#evaluate-the-hypotheses">Evaluate the hypotheses</a></li>
  <li><a href="#locate-the-models-success-and-failure" id="toc-locate-the-models-success-and-failure" class="nav-link" data-scroll-target="#locate-the-models-success-and-failure">Locate the model’s success and failure</a></li>
  <li><a href="#read-a-few-held-out-predictions" id="toc-read-a-few-held-out-predictions" class="nav-link" data-scroll-target="#read-a-few-held-out-predictions">Read a few held-out predictions</a></li>
  <li><a href="#what-the-application-establishes" id="toc-what-the-application-establishes" class="nav-link" data-scroll-target="#what-the-application-establishes">What the application establishes</a></li>
  <li><a href="#check-the-reasoning" id="toc-check-the-reasoning" class="nav-link" data-scroll-target="#check-the-reasoning">Check the reasoning</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../factorization/index.html">Factorization</a></li><li class="breadcrumb-item"><a href="../factorization/valex-megaacceptability.html">Can corpus distributions predict clause selection?</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Can corpus distributions predict clause selection?</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Clause embedding verbs differ in the complements they permit. <em>Think</em> occurs naturally with a declarative clause, as in <em>Someone thought that something happened</em>. <em>Wonder</em> occurs naturally with an interrogative clause, as in <em>Someone wondered whether something happened</em>. <em>Persuade</em> instead favors an object followed by an infinitive, as in <em>Someone persuaded someone to do something</em>.</p>
<p>These differences define a verb’s <a href="https://doi.org/10.5334/gjgl.1001"><strong>selectional profile</strong></a>. The question on this page is whether a verb’s distribution in a large corpus predicts that profile.</p>
<p>We will build the analysis in four stages. First, we will define the corpus predictor and acceptability response. Second, we will state two linguistic hypotheses that distinguish a complete distribution from a compressed distribution. Third, we will compare those representations on verbs excluded from fitting. Finally, we will inspect where the predictions succeed and fail.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Reading: White and Rawlins (2020)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading: White and Rawlins (2020)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Read Sections 1, 2.4, 5, and 6 and Appendix C of <a href="https://doi.org/10.5334/gjgl.1001">White and Rawlins, <em>Frequency, acceptability, and selection: A case study of clause-embedding</em></a>.</p>
<p>Section 1 motivates the relation between corpus frequency and selection. Section 2.4 states the frequency and abstraction hypotheses. Section 5 tests direct distributional predictors, while Section 6 tests compressed abstractions of the corpus distributions. Appendix C compares response normalization procedures. The reading is included because these parts separate the linguistic claim from the particular statistical implementation used to test it.</p>
</div>
</div>
<section id="start-with-the-linguistic-observations" class="level2">
<h2 class="anchored" data-anchor-id="start-with-the-linguistic-observations">Start with the linguistic observations</h2>
<p>MegaAcceptability contains judgments for 1,000 English clause embedding verbs in 50 surface syntactic frames. Each original verb by frame cell received five judgments on a scale from 1 to 7. The frames vary several properties of the complement, including clause type, tense, the presence of an object, and the eventive or stative interpretation of an infinitive.</p>
<p>The intersection with the usable VALEX inventory contains 958 verbs. Restricting the raw judgments to those verbs, omitting ten missing responses, and retaining participants who reported being native speakers of American English leaves 238,917 responses from 727 participants. Every analysis below uses that fixed intersection.</p>
<p>Consider five cells from the dataset.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>verb</th>
<th>frame</th>
<th>sentence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>think</em></td>
<td><code>NP Ved that S</code></td>
<td>Someone thought that something happened.</td>
</tr>
<tr class="even">
<td><em>persuade</em></td>
<td><code>NP Ved NP to VP[+eventive]</code></td>
<td>Someone persuaded someone to do something.</td>
</tr>
<tr class="odd">
<td><em>wonder</em></td>
<td><code>NP Ved whether S</code></td>
<td>Someone wondered whether something happened.</td>
</tr>
<tr class="even">
<td><em>try</em></td>
<td><code>NP Ved to VP[+eventive]</code></td>
<td>Someone tried to do something.</td>
</tr>
<tr class="odd">
<td><em>promise</em></td>
<td><code>NP Ved to VP[+eventive]</code></td>
<td>Someone promised to do something.</td>
</tr>
</tbody>
</table>
<p>The notation abstracts away from the particular nouns and embedded predicates in the stimuli. <code>NP Ved whether S</code>, for instance, records a past tense matrix verb followed by an interrogative clause. This makes the response matrix about complement selection rather than about one particular sentence.</p>
<p>Let <span class="math inline">y_{vk}</span> denote the normalized acceptability of verb <span class="math inline">v</span> in MegaAcceptability frame <span class="math inline">k</span>. One row of the response matrix is then</p>
<p><span class="math display">
\mathbf{y}_v
=
\begin{bmatrix}
y_{v1} &amp; y_{v2} &amp; \cdots &amp; y_{v,50}
\end{bmatrix}.
</span></p>
<p>The complete response matrix <span class="math inline">\mathbf{Y}</span> has one row for each retained verb and 50 columns. This is the object we want to predict.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Reasoning check">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reasoning check
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we instead placed individual ratings in the rows, would a row still represent a selectional profile?</p>
<p>No.&nbsp;A row would represent one participant’s response to one sentence. Constructing a verb profile requires us to say how those responses are combined and how participant use of the response scale is handled.</p>
</div>
</div>
</section>
<section id="interpret-the-normalized-response-scale" class="level2">
<h2 class="anchored" data-anchor-id="interpret-the-normalized-response-scale">Interpret the normalized response scale</h2>
<p>Participants may use the seven response categories differently. One participant may use almost the complete scale, while another may concentrate responses between 3 and 6. Treating their raw numbers as if they shared an origin and unit may preserve variation in response habits that is not part of verb selection. We will use the training based transformation developed in <a href="../factorization/centering-and-scaling.html">centering and scaling</a>.</p>
<p>For a particular training set of verbs, let <span class="math inline">\bar r_{p,\mathcal T}</span> be participant <span class="math inline">p</span>’s mean rating and let <span class="math inline">s_{p,\mathcal T}</span> be the corresponding standard deviation. We transform each rating using</p>
<p><span class="math display">
z_{pi}
=
\frac{r_{pi}-\bar r_{p,\mathcal T}}
     {s_{p,\mathcal T}}.
</span></p>
<p>We then average the transformed ratings within each verb by frame cell. A normalized value of 1 means that the responses to that cell were, on average, one participant specific standard deviation above the participants’ training means. A value of 0 marks the relevant participant baselines. It does not mark a boundary between grammatical and ungrammatical sentences.</p>
<p>This interpretation also explains why a difference of one normalized unit is not a difference of one point on the original response scale. The normalized scale is relative. Its origin and unit come from the training responses.</p>
<p>The training qualification matters. If a test verb helped determine a participant’s mean or standard deviation, its response would affect its own normalization before prediction. To avoid <a href="../model-criticism-and-prediction/training-and-test-data.html#leakage">data leakage</a>, fit the participant transformation on training verbs and apply those fixed values to test responses.</p>
<p>One participant had a zero training standard deviation in one of the 300 normalization fits used below. The prespecified fallback used the overall training mean and standard deviation for that participant. No participant lacked training responses. Thus the fallback repaired an undefined division without consulting a validation or test response.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="What this normalization does not establish">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What this normalization does not establish
</div>
</div>
<div class="callout-body-container callout-body">
<p>The responses are ordinal. Subtracting a mean and dividing by a standard deviation treats adjacent response categories as equally spaced for this preprocessing step. That is an approximation, not a trial level model of ordinal judgments.</p>
<p>White and Rawlins use a more elaborate ordinal normalization. Across the 47,900 verb by frame cells used here, the training style transformation fitted to the complete retained sample correlates 0.946 with their released normalized values. The simpler transformation tracks the released profiles closely enough for this factorization application, while allowing every fitted quantity to remain inside its training fold.</p>
</div>
</div>
</section>
<section id="construct-the-corpus-predictor" class="level2">
<h2 class="anchored" data-anchor-id="construct-the-corpus-predictor">Construct the corpus predictor</h2>
<p>VALEX is a corpus derived lexicon of verb subcategorization frequencies. For each verb, it records counts for syntactic patterns such as a sentential complement, an infinitival complement, an object, or no detected complement. The released analysis distinguishes 109 frame and class combinations among the verbs shared with MegaAcceptability.</p>
<p>Let <span class="math inline">c_{vj}</span> be the VALEX count for verb <span class="math inline">v</span> in corpus frame <span class="math inline">j</span>. Raw counts mix two kinds of information: the total number of corpus occurrences for the verb and the allocation of those occurrences across frames. The analysis concerns the allocation, so we convert each count to a within verb proportion:</p>
<p><span class="math display">
x_{vj}
=
\frac{c_{vj}}
     {\sum_{h=1}^{109} c_{vh}}.
</span></p>
<p>The row</p>
<p><span class="math display">
\mathbf{x}_v
=
\begin{bmatrix}
x_{v1} &amp; x_{v2} &amp; \cdots &amp; x_{v,109}
\end{bmatrix}
</span></p>
<p>is the verb’s normalized VALEX frame distribution. Its entries are nonnegative and sum to one.</p>
<p>The following table collapses the VALEX class distinctions only to make three profiles readable. The fitted model retains all 109 original columns.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>verb</th>
<th>largest corpus frame</th>
<th style="text-align: right;">proportion</th>
<th>next largest corpus frame</th>
<th style="text-align: right;">proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>think</em></td>
<td>sentential complement</td>
<td style="text-align: right;">0.501</td>
<td>no detected complement</td>
<td style="text-align: right;">0.322</td>
</tr>
<tr class="even">
<td><em>persuade</em></td>
<td>infinitival complement with subject</td>
<td style="text-align: right;">0.533</td>
<td>noun phrase</td>
<td style="text-align: right;">0.237</td>
</tr>
<tr class="odd">
<td><em>try</em></td>
<td>verbal infinitive</td>
<td style="text-align: right;">0.646</td>
<td>no detected complement</td>
<td style="text-align: right;">0.157</td>
</tr>
</tbody>
</table>
<p>These are theoretically relevant predictors. The high sentential complement proportion for <em>think</em> and the high infinitival proportion for <em>try</em> encode distributional facts that a theory of selection should connect to their acceptability profiles. The predictor is not merely verb frequency, word length, or an arbitrary vector supplied to the model.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Reasoning check">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reasoning check
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why not use the total VALEX count as the only predictor?</p>
<p>Total count measures how often a verb was observed. It does not say which complements the verb occurred with. Two verbs can have the same total count and very different distributions across sentential, infinitival, and nominal frames.</p>
</div>
</div>
</section>
<section id="state-the-two-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="state-the-two-hypotheses">State the two hypotheses</h2>
<p>The first hypothesis concerns the complete direct profile.</p>
<p>First, the complete 109 dimensional VALEX distribution for a verb may predict its 50 dimensional MegaAcceptability profile.</p>
<p>This hypothesis concerns generalization to verbs, not filling a randomly hidden cell for a verb already seen during fitting. A successful test must thus exclude complete verbs.</p>
<p>The second hypothesis concerns abstraction.</p>
<p>Second, a lower dimensional representation of the VALEX distribution may predict the MegaAcceptability profile better than the complete distribution.</p>
<p>The motivation for the second hypothesis is that raw corpus frames may divide evidence too finely. Several observed frames might express a shared syntactic or semantic distinction. If PCA recovers that shared structure, a small number of scores might preserve the predictive regularity while discarding frame specific noise.</p>
<p>Compression alone does not constitute linguistic abstraction. PCA orders directions by variation in the VALEX matrix, not by their relation to a theory of clause selection. The comparison tests whether this particular shallow abstraction improves prediction. It cannot show that the selected components are grammatical primitives.</p>
</section>
<section id="change-only-the-predictor-representation" class="level2">
<h2 class="anchored" data-anchor-id="change-only-the-predictor-representation">Change only the predictor representation</h2>
<p>The direct model uses the complete row <span class="math inline">\mathbf{x}_v</span>. For each of the 50 response columns, <a href="../regression-models/ridge-regression.html">ridge regression</a> predicts normalized acceptability from the same 109 predictors. Writing all response columns together gives</p>
<p><span class="math display">
\widehat{\mathbf{Y}}_{\mathrm{direct}}
=
\mathbf{1}\boldsymbol{\beta}_0^{\mathsf T}
+
\mathbf{X}\mathbf{B}.
</span></p>
<p>This matrix expression is just 50 ridge regressions sharing a predictor matrix and penalty. It does not introduce a different response model.</p>
<p>The factor model changes one part of the procedure. We center the VALEX columns using the training verbs, fit <a href="../factorization/principal-component-analysis.html">PCA</a> to those training rows, and retain the first <span class="math inline">K</span> scores:</p>
<p><span class="math display">
\mathbf{Z}_K
=
\left(
\mathbf{X}
-
\mathbf{1}\boldsymbol{\mu}_{\mathcal T}^{\mathsf T}
\right)
\mathbf{V}_{\mathcal T,K}.
</span></p>
<p>Ridge regression then predicts the same response matrix from <span class="math inline">\mathbf{Z}_K</span>:</p>
<p><span class="math display">
\widehat{\mathbf{Y}}_{\mathrm{factor}}
=
\mathbf{1}\boldsymbol{\gamma}_0^{\mathsf T}
+
\mathbf{Z}_K\mathbf{G}.
</span></p>
<p>The models have the same verbs, the same responses, the same loss, and the same type of ridge regression. Their difference is whether the ridge regression receives 109 direct proportions or <span class="math inline">K</span> PCA scores. This isolates the comparison between the complete distribution and its lower dimensional representation.</p>
</section>
<section id="keep-every-fitted-choice-inside-the-training-data" class="level2">
<h2 class="anchored" data-anchor-id="keep-every-fitted-choice-inside-the-training-data">Keep every fitted choice inside the training data</h2>
<p>The outer evaluation uses five repetitions of <a href="../model-criticism-and-prediction/grouped-cross-validation.html">ten fold grouped cross validation</a>. Each outer fold excludes complete verbs. Within its training verbs, five fold validation applies the <a href="../factorization/choosing-components.html">component selection procedure</a> to the factor model. It selects the ridge penalty for the direct model and jointly selects the retained rank and ridge penalty for the factor model.</p>
<p>The fitting sequence for one outer fold is:</p>
<ol type="1">
<li>Set aside the outer test verbs.</li>
<li>Split the remaining verbs into inner training and validation sets.</li>
<li>Fit participant normalization on the inner training responses.</li>
<li>Fit PCA centering and component directions on the inner training VALEX rows.</li>
<li>Evaluate each fixed rank and ridge candidate on the inner validation verbs.</li>
<li>Select the candidates with the lowest inner validation squared loss.</li>
<li>Refit normalization, PCA, and ridge regression on all outer training verbs.</li>
<li>Evaluate the selected procedures once on the outer test verbs.</li>
</ol>
<p>The ridge candidates are <span class="math inline">0.01</span>, <span class="math inline">0.1</span>, <span class="math inline">0.2</span>, <span class="math inline">0.5</span>, <span class="math inline">1</span>, <span class="math inline">2</span>, <span class="math inline">5</span>, and <span class="math inline">10</span>. The rank candidates are <span class="math inline">2</span>, <span class="math inline">5</span>, <span class="math inline">10</span>, <span class="math inline">20</span>, <span class="math inline">30</span>, <span class="math inline">40</span>, and <span class="math inline">50</span>. These sets were fixed before the outer results were inspected.</p>
<p>Why must PCA be fitted again inside every inner split? Suppose an inner validation verb has an unusual concentration in one VALEX frame. If that row helps determine the component direction, its distribution has already influenced its own representation. The later ridge fit does not remove this <a href="../model-criticism-and-prediction/training-and-test-data.html#leakage">data leakage</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Reasoning check">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reasoning check
</div>
</div>
<div class="callout-body-container callout-body">
<p>May we compute one PCA from all 958 verbs because the PCA does not use acceptability?</p>
<p>No.&nbsp;The target is prediction for a new verb. Its VALEX row is part of the information withheld under that target. Using the row to fit the component directions gives the factor model access to the test verb before evaluation.</p>
</div>
</div>
</section>
<section id="define-the-predictive-score" class="level2">
<h2 class="anchored" data-anchor-id="define-the-predictive-score">Define the predictive score</h2>
<p>The baseline predicts the training mean separately for each of the 50 MegaAcceptability frames. It knows that some frames tend to receive higher judgments than others, but it does not use the identity or VALEX profile of the test verb.</p>
<p>For a fitted model <span class="math inline">m</span>, define out-of-sample <span class="math inline">R^2</span> relative to the frame-mean baseline as</p>
<p><span class="math display">
R^2_m
=
1
-
\frac{
\sum_i (y_i-\widehat y_{m,i})^2
}{
\sum_i (y_i-\widehat y_{\mathrm{base},i})^2
}.
</span></p>
<p>A value of 0 means that the model matches the frame mean baseline. A positive value means that the verb specific prediction removes some of the baseline squared error. A negative value means that it does worse than the baseline.</p>
<p>The difference</p>
<p><span class="math display">
\Delta R^2
=
R^2_{\mathrm{factor}}
-
R^2_{\mathrm{direct}}
</span></p>
<p>tests the second hypothesis. Positive values favor compression. Negative values favor the complete distribution.</p>
<p>Uncertainty is computed with the <a href="../statistical-inference/bootstrap-confidence-intervals.html">bootstrap</a> by resampling verbs. Each sampled verb contributes all of its frames and all five outer predictions. This preserves the paired comparison between representations and respects the verb as the held-out unit.</p>
</section>
<section id="evaluate-the-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="evaluate-the-hypotheses">Evaluate the hypotheses</h2>
<p>Before this analysis, we decided that the first hypothesis would count as supported only if direct out-of-sample <span class="math inline">R^2</span> reached at least 0.20, its verb bootstrap interval lay above zero, and <span class="math inline">R^2</span> was positive in every repetition. We treated the difference between representations as stable if its interval excluded zero or lay completely between <span class="math inline">-0.01</span> and <span class="math inline">0.01</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>representation</th>
<th style="text-align: right;">out-of-sample <span class="math inline">R^2</span></th>
<th style="text-align: right;">95 percent verb interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>direct VALEX profile</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">[0.224, 0.266]</td>
</tr>
<tr class="even">
<td>50 component VALEX profile</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">[0.218, 0.259]</td>
</tr>
<tr class="odd">
<td>factor minus direct</td>
<td style="text-align: right;">-0.0066</td>
<td style="text-align: right;">[-0.0100, -0.0029]</td>
</tr>
</tbody>
</table>
<p>The direct model meets all three criteria. Its repetition-specific <span class="math inline">R^2</span> ranges from 0.238 to 0.250, so the result does not depend on one favorable division of the verbs.</p>
<p>The factor model does not support the second hypothesis. Inner validation selected 50 components in all 50 outer folds, which is the largest permitted factor rank. Even that representation has an out-of-sample <span class="math inline">R^2</span> that is 0.0066 lower than the direct profile, and the difference is negative in all five repetitions. The result is small but stable.</p>
<p>This is an informative failure of compression. The direct corpus distribution predicts new selectional profiles, but the PCA directions with the most corpus variation do not preserve all of the information useful for that prediction.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Reasoning check">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reasoning check
</div>
</div>
<div class="callout-body-container callout-body">
<p>Does selecting 50 components show that English clause selection has 50 latent dimensions?</p>
<p>No.&nbsp;It shows that 50 was the best candidate rank for this predictor, response, loss, and candidate set. Since it was also the largest candidate, the validation results suggest that additional VALEX directions may remain useful. They do not identify a true number of grammatical dimensions.</p>
</div>
</div>
</section>
<section id="locate-the-models-success-and-failure" class="level2">
<h2 class="anchored" data-anchor-id="locate-the-models-success-and-failure">Locate the model’s success and failure</h2>
<p>An overall score can hide a theoretically organized error. White and Rawlins observe that direct corpus prediction is especially weak when an object precedes a finite clause. We fixed that comparison before inspecting the new pilot.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>frame family</th>
<th style="text-align: right;">number of frames</th>
<th style="text-align: right;">direct <span class="math inline">R^2</span></th>
<th style="text-align: right;">factor <span class="math inline">R^2</span></th>
<th style="text-align: right;">factor minus direct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>finite clause without object</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.254</td>
<td style="text-align: right;">0.238</td>
<td style="text-align: right;">-0.0156</td>
</tr>
<tr class="even">
<td>finite clause with direct object</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">0.0010</td>
</tr>
<tr class="odd">
<td>finite declarative</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.212</td>
<td style="text-align: right;">0.202</td>
<td style="text-align: right;">-0.0105</td>
</tr>
<tr class="even">
<td>finite interrogative</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">-0.0116</td>
</tr>
<tr class="odd">
<td>eventive infinitive</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.268</td>
<td style="text-align: right;">0.264</td>
<td style="text-align: right;">-0.0035</td>
</tr>
<tr class="even">
<td>stative infinitive</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.285</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">-0.0065</td>
</tr>
</tbody>
</table>
<p>The object contrast is much larger than the declarative, interrogative, or infinitival contrasts. Direct out-of-sample <span class="math inline">R^2</span> falls from 0.254 for finite clauses without an object to 0.083 for their matched object frames. At the individual frame level, direct <span class="math inline">R^2</span> is 0.037 for <code>NP Ved NP whether S</code>, 0.061 for <code>NP Ved NP whichNP S</code>, and 0.109 for <code>NP Ved NP that S</code>. Their counterparts without an object have values of 0.249, 0.290, and 0.270.</p>
<p>PCA does not repair this family level failure. Its <span class="math inline">R^2</span> is only 0.0010 higher for the five object frames and 0.0156 lower for the matched frames without an object. Thus the stable overall loss and the small local gain are compatible: compression discards useful information in the frames that already work, and restores very little where the direct mapping fails.</p>
<p>White and Rawlins connect the object pattern to communicativity. A verb such as <em>persuade</em> may license a finite clause after an object because the object refers to a recipient of communicated content. Corpus cooccurrence can register the surface sequence without directly representing that semantic relation. The error pattern is consistent with this proposal, though it does not isolate communicativity from animacy, discourse, or errors in automatic corpus analysis.</p>
</section>
<section id="read-a-few-held-out-predictions" class="level2">
<h2 class="anchored" data-anchor-id="read-a-few-held-out-predictions">Read a few held-out predictions</h2>
<p>The following values average the five held-out predictions for the fixed example verbs. Positive observed values indicate responses above the relevant participant training baselines.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>verb and frame</th>
<th style="text-align: right;">observed</th>
<th style="text-align: right;">direct</th>
<th style="text-align: right;">factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>think</em> with <code>that S</code></td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">1.55</td>
<td style="text-align: right;">1.58</td>
</tr>
<tr class="even">
<td><em>persuade</em> with <code>NP to VP[+eventive]</code></td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">1.58</td>
</tr>
<tr class="odd">
<td><em>wonder</em> with <code>whether S</code></td>
<td style="text-align: right;">2.77</td>
<td style="text-align: right;">3.95</td>
<td style="text-align: right;">4.01</td>
</tr>
<tr class="even">
<td><em>try</em> with <code>to VP[+eventive]</code></td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">2.54</td>
<td style="text-align: right;">2.57</td>
</tr>
<tr class="odd">
<td><em>promise</em> with <code>to VP[+eventive]</code></td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">1.10</td>
</tr>
<tr class="even">
<td><em>persuade</em> with <code>NP that S</code></td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: right;">-0.07</td>
</tr>
</tbody>
</table>
<p>The <em>persuade</em> infinitive is predicted closely, while its object plus finite clause is missed by more than one normalized unit. The contrast shows why a profile level score and a frame family diagnostic are both needed. The model has learned something about <em>persuade</em>, but it has not learned every route by which the verb licenses a content clause.</p>
<p>The overprediction for <em>wonder</em> and <em>try</em> raises a second issue. Ridge predictions are not constrained to the range of observed cell means. More importantly, a large error for a high acceptability cell can coexist with correct ordering elsewhere in the 50 dimensional profile. The squared error score evaluates both ordering and calibration. A different loss would define a different predictive target.</p>
</section>
<section id="what-the-application-establishes" class="level2">
<h2 class="anchored" data-anchor-id="what-the-application-establishes">What the application establishes</h2>
<p>The analysis supports three conclusions.</p>
<ol type="1">
<li>VALEX complement distributions contain information about the acceptability profiles of verbs excluded from fitting.</li>
<li>PCA compression does not improve this mapping. Nested validation consistently retains the largest candidate rank, and the selected factor model performs slightly worse than the direct profile.</li>
<li>Prediction remains especially weak for an object followed by a finite clause. The error is organized by a theoretically relevant construction rather than spread uniformly across the response matrix.</li>
</ol>
<p>These conclusions are narrower than a claim that selection reduces to frequency. VALEX is a noisy corpus measurement, MegaAcceptability is an aggregate judgment measurement, and ridge regression estimates a predictive association. The remaining object frame error may point to semantic information absent from the corpus frame inventory, but the present comparison does not identify that information.</p>
<p>The live question is thus more specific than whether abstraction matters. Which representation of communicativity, argument structure, or event structure predicts the object plus finite clause contrast without sacrificing the direct distributional signal in the other frames? Answering that question would require a new theoretically specified predictor and a new held-out comparison. It cannot be answered by renaming the present principal components.</p>
</section>
<section id="check-the-reasoning" class="level2">
<h2 class="anchored" data-anchor-id="check-the-reasoning">Check the reasoning</h2>
<ol type="1">
<li>What does one row of the VALEX matrix represent?</li>
<li>Why are VALEX counts converted to within verb proportions?</li>
<li>What is the held-out unit, and which linguistic claim makes that unit appropriate?</li>
<li>Which quantities must be refitted inside an inner training split?</li>
<li>What is held constant between the direct and factor models?</li>
<li>Why does a selected rank of 50 not identify 50 grammatical categories?</li>
<li>Which frame family produces the most pronounced direct prediction failure?</li>
<li>Does a small stable loss for PCA imply that no abstract representation could improve the mapping?</li>
</ol>
<p>The final question is the main scope check. This analysis rejects one shallow predictive compression, not abstraction in general. A future abstraction must earn its interpretation through theoretically defined inputs, fold safe fitting, and improved prediction on verbs that did not determine it.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../factorization/choosing-components.html" class="pagination-link" aria-label="Choosing the number of components">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Choosing the number of components</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../missing-data/index.html" class="pagination-link" aria-label="Missing data">
        <span class="nav-page-text">Missing data</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Can corpus distributions predict clause selection?"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Clause embedding verbs differ in the complements they permit. *Think* occurs naturally with a declarative clause, as in *Someone thought that something happened*. *Wonder* occurs naturally with an interrogative clause, as in *Someone wondered whether something happened*. *Persuade* instead favors an object followed by an infinitive, as in *Someone persuaded someone to do something*.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>These differences define a verb's <span class="co">[</span><span class="ot">**selectional profile**</span><span class="co">](https://doi.org/10.5334/gjgl.1001)</span>. The question on this page is whether a verb's distribution in a large corpus predicts that profile.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>We will build the analysis in four stages. First, we will define the corpus predictor and acceptability response. Second, we will state two linguistic hypotheses that distinguish a complete distribution from a compressed distribution. Third, we will compare those representations on verbs excluded from fitting. Finally, we will inspect where the predictions succeed and fail.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Reading: White and Rawlins (2020)"}</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>Read Sections 1, 2.4, 5, and 6 and Appendix C of <span class="co">[</span><span class="ot">White and Rawlins, *Frequency, acceptability, and selection: A case study of clause-embedding*</span><span class="co">](https://doi.org/10.5334/gjgl.1001)</span>.</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>Section 1 motivates the relation between corpus frequency and selection. Section 2.4 states the frequency and abstraction hypotheses. Section 5 tests direct distributional predictors, while Section 6 tests compressed abstractions of the corpus distributions. Appendix C compares response normalization procedures. The reading is included because these parts separate the linguistic claim from the particular statistical implementation used to test it.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Start with the linguistic observations</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>MegaAcceptability contains judgments for 1,000 English clause embedding verbs in 50 surface syntactic frames. Each original verb by frame cell received five judgments on a scale from 1 to 7. The frames vary several properties of the complement, including clause type, tense, the presence of an object, and the eventive or stative interpretation of an infinitive.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>The intersection with the usable VALEX inventory contains 958 verbs. Restricting the raw judgments to those verbs, omitting ten missing responses, and retaining participants who reported being native speakers of American English leaves 238,917 responses from 727 participants. Every analysis below uses that fixed intersection.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>Consider five cells from the dataset.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> verb <span class="pp">|</span> frame <span class="pp">|</span> sentence <span class="pp">|</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *think* <span class="pp">|</span> <span class="in">`NP Ved that S`</span> <span class="pp">|</span> Someone thought that something happened. <span class="pp">|</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *persuade* <span class="pp">|</span> <span class="in">`NP Ved NP to VP[+eventive]`</span> <span class="pp">|</span> Someone persuaded someone to do something. <span class="pp">|</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *wonder* <span class="pp">|</span> <span class="in">`NP Ved whether S`</span> <span class="pp">|</span> Someone wondered whether something happened. <span class="pp">|</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *try* <span class="pp">|</span> <span class="in">`NP Ved to VP[+eventive]`</span> <span class="pp">|</span> Someone tried to do something. <span class="pp">|</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *promise* <span class="pp">|</span> <span class="in">`NP Ved to VP[+eventive]`</span> <span class="pp">|</span> Someone promised to do something. <span class="pp">|</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>The notation abstracts away from the particular nouns and embedded predicates in the stimuli. <span class="in">`NP Ved whether S`</span>, for instance, records a past tense matrix verb followed by an interrogative clause. This makes the response matrix about complement selection rather than about one particular sentence.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Let $y_{vk}$ denote the normalized acceptability of verb $v$ in MegaAcceptability frame $k$. One row of the response matrix is then</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>\mathbf{y}_v</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>\begin{bmatrix}</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>y_{v1} &amp; y_{v2} &amp; \cdots &amp; y_{v,50}</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>\end{bmatrix}.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>The complete response matrix $\mathbf{Y}$ has one row for each retained verb and 50 columns. This is the object we want to predict.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Reasoning check"}</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>If we instead placed individual ratings in the rows, would a row still represent a selectional profile?</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>No. A row would represent one participant's response to one sentence. Constructing a verb profile requires us to say how those responses are combined and how participant use of the response scale is handled.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpret the normalized response scale</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>Participants may use the seven response categories differently. One participant may use almost the complete scale, while another may concentrate responses between 3 and 6. Treating their raw numbers as if they shared an origin and unit may preserve variation in response habits that is not part of verb selection. We will use the training based transformation developed in <span class="co">[</span><span class="ot">centering and scaling</span><span class="co">](centering-and-scaling.qmd)</span>.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>For a particular training set of verbs, let $\bar r_{p,\mathcal T}$ be participant $p$'s mean rating and let $s_{p,\mathcal T}$ be the corresponding standard deviation. We transform each rating using</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>z_{pi}</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>\frac{r_{pi}-\bar r_{p,\mathcal T}}</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>     {s_{p,\mathcal T}}.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>We then average the transformed ratings within each verb by frame cell. A normalized value of 1 means that the responses to that cell were, on average, one participant specific standard deviation above the participants' training means. A value of 0 marks the relevant participant baselines. It does not mark a boundary between grammatical and ungrammatical sentences.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>This interpretation also explains why a difference of one normalized unit is not a difference of one point on the original response scale. The normalized scale is relative. Its origin and unit come from the training responses.</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>The training qualification matters. If a test verb helped determine a participant's mean or standard deviation, its response would affect its own normalization before prediction. To avoid <span class="co">[</span><span class="ot">data leakage</span><span class="co">](../model-criticism-and-prediction/training-and-test-data.qmd#leakage)</span>, fit the participant transformation on training verbs and apply those fixed values to test responses.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>One participant had a zero training standard deviation in one of the 300 normalization fits used below. The prespecified fallback used the overall training mean and standard deviation for that participant. No participant lacked training responses. Thus the fallback repaired an undefined division without consulting a validation or test response.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="What this normalization does not establish"}</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>The responses are ordinal. Subtracting a mean and dividing by a standard deviation treats adjacent response categories as equally spaced for this preprocessing step. That is an approximation, not a trial level model of ordinal judgments.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>White and Rawlins use a more elaborate ordinal normalization. Across the 47,900 verb by frame cells used here, the training style transformation fitted to the complete retained sample correlates 0.946 with their released normalized values. The simpler transformation tracks the released profiles closely enough for this factorization application, while allowing every fitted quantity to remain inside its training fold.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="fu">## Construct the corpus predictor</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>VALEX is a corpus derived lexicon of verb subcategorization frequencies. For each verb, it records counts for syntactic patterns such as a sentential complement, an infinitival complement, an object, or no detected complement. The released analysis distinguishes 109 frame and class combinations among the verbs shared with MegaAcceptability.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>Let $c_{vj}$ be the VALEX count for verb $v$ in corpus frame $j$. Raw counts mix two kinds of information: the total number of corpus occurrences for the verb and the allocation of those occurrences across frames. The analysis concerns the allocation, so we convert each count to a within verb proportion:</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>x_{vj}</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>\frac{c_{vj}}</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>     {\sum_{h=1}^{109} c_{vh}}.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>The row</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>\mathbf{x}_v</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>\begin{bmatrix}</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>x_{v1} &amp; x_{v2} &amp; \cdots &amp; x_{v,109}</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>\end{bmatrix}</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>is the verb's normalized VALEX frame distribution. Its entries are nonnegative and sum to one.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>The following table collapses the VALEX class distinctions only to make three profiles readable. The fitted model retains all 109 original columns.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> verb <span class="pp">|</span> largest corpus frame <span class="pp">|</span> proportion <span class="pp">|</span> next largest corpus frame <span class="pp">|</span> proportion <span class="pp">|</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|---|---:|</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *think* <span class="pp">|</span> sentential complement <span class="pp">|</span> 0.501 <span class="pp">|</span> no detected complement <span class="pp">|</span> 0.322 <span class="pp">|</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *persuade* <span class="pp">|</span> infinitival complement with subject <span class="pp">|</span> 0.533 <span class="pp">|</span> noun phrase <span class="pp">|</span> 0.237 <span class="pp">|</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *try* <span class="pp">|</span> verbal infinitive <span class="pp">|</span> 0.646 <span class="pp">|</span> no detected complement <span class="pp">|</span> 0.157 <span class="pp">|</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>These are theoretically relevant predictors. The high sentential complement proportion for *think* and the high infinitival proportion for *try* encode distributional facts that a theory of selection should connect to their acceptability profiles. The predictor is not merely verb frequency, word length, or an arbitrary vector supplied to the model.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Reasoning check"}</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>Why not use the total VALEX count as the only predictor?</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>Total count measures how often a verb was observed. It does not say which complements the verb occurred with. Two verbs can have the same total count and very different distributions across sentential, infinitival, and nominal frames.</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="fu">## State the two hypotheses</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>The first hypothesis concerns the complete direct profile.</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>First, the complete 109 dimensional VALEX distribution for a verb may predict its 50 dimensional MegaAcceptability profile.</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>This hypothesis concerns generalization to verbs, not filling a randomly hidden cell for a verb already seen during fitting. A successful test must thus exclude complete verbs.</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>The second hypothesis concerns abstraction.</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>Second, a lower dimensional representation of the VALEX distribution may predict the MegaAcceptability profile better than the complete distribution.</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>The motivation for the second hypothesis is that raw corpus frames may divide evidence too finely. Several observed frames might express a shared syntactic or semantic distinction. If PCA recovers that shared structure, a small number of scores might preserve the predictive regularity while discarding frame specific noise.</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>Compression alone does not constitute linguistic abstraction. PCA orders directions by variation in the VALEX matrix, not by their relation to a theory of clause selection. The comparison tests whether this particular shallow abstraction improves prediction. It cannot show that the selected components are grammatical primitives.</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="fu">## Change only the predictor representation</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>The direct model uses the complete row $\mathbf{x}_v$. For each of the 50 response columns, <span class="co">[</span><span class="ot">ridge regression</span><span class="co">](../regression-models/ridge-regression.qmd)</span> predicts normalized acceptability from the same 109 predictors. Writing all response columns together gives</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>\widehat{\mathbf{Y}}_{\mathrm{direct}}</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>\mathbf{1}\boldsymbol{\beta}_0^{\mathsf T}</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>+</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>\mathbf{X}\mathbf{B}.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>This matrix expression is just 50 ridge regressions sharing a predictor matrix and penalty. It does not introduce a different response model.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>The factor model changes one part of the procedure. We center the VALEX columns using the training verbs, fit <span class="co">[</span><span class="ot">PCA</span><span class="co">](principal-component-analysis.qmd)</span> to those training rows, and retain the first $K$ scores:</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>\mathbf{Z}_K</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>\left(</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>\mathbf{X}</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>-</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>\mathbf{1}\boldsymbol{\mu}_{\mathcal T}^{\mathsf T}</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>\right)</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>\mathbf{V}_{\mathcal T,K}.</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>Ridge regression then predicts the same response matrix from $\mathbf{Z}_K$:</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>\widehat{\mathbf{Y}}_{\mathrm{factor}}</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>\mathbf{1}\boldsymbol{\gamma}_0^{\mathsf T}</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>+</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>\mathbf{Z}_K\mathbf{G}.</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>The models have the same verbs, the same responses, the same loss, and the same type of ridge regression. Their difference is whether the ridge regression receives 109 direct proportions or $K$ PCA scores. This isolates the comparison between the complete distribution and its lower dimensional representation.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Keep every fitted choice inside the training data</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>The outer evaluation uses five repetitions of <span class="co">[</span><span class="ot">ten fold grouped cross validation</span><span class="co">](../model-criticism-and-prediction/grouped-cross-validation.qmd)</span>. Each outer fold excludes complete verbs. Within its training verbs, five fold validation applies the <span class="co">[</span><span class="ot">component selection procedure</span><span class="co">](choosing-components.qmd)</span> to the factor model. It selects the ridge penalty for the direct model and jointly selects the retained rank and ridge penalty for the factor model.</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>The fitting sequence for one outer fold is:</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Set aside the outer test verbs.</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Split the remaining verbs into inner training and validation sets.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Fit participant normalization on the inner training responses.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Fit PCA centering and component directions on the inner training VALEX rows.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Evaluate each fixed rank and ridge candidate on the inner validation verbs.</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Select the candidates with the lowest inner validation squared loss.</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Refit normalization, PCA, and ridge regression on all outer training verbs.</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Evaluate the selected procedures once on the outer test verbs.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>The ridge candidates are $0.01$, $0.1$, $0.2$, $0.5$, $1$, $2$, $5$, and $10$. The rank candidates are $2$, $5$, $10$, $20$, $30$, $40$, and $50$. These sets were fixed before the outer results were inspected.</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>Why must PCA be fitted again inside every inner split? Suppose an inner validation verb has an unusual concentration in one VALEX frame. If that row helps determine the component direction, its distribution has already influenced its own representation. The later ridge fit does not remove this <span class="co">[</span><span class="ot">data leakage</span><span class="co">](../model-criticism-and-prediction/training-and-test-data.qmd#leakage)</span>.</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Reasoning check"}</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>May we compute one PCA from all 958 verbs because the PCA does not use acceptability?</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>No. The target is prediction for a new verb. Its VALEX row is part of the information withheld under that target. Using the row to fit the component directions gives the factor model access to the test verb before evaluation.</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="fu">## Define the predictive score</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>The baseline predicts the training mean separately for each of the 50 MegaAcceptability frames. It knows that some frames tend to receive higher judgments than others, but it does not use the identity or VALEX profile of the test verb.</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>For a fitted model $m$, define out-of-sample $R^2$ relative to the frame-mean baseline as</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>R^2_m</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>1</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>-</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>\frac{</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>\sum_i (y_i-\widehat y_{m,i})^2</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>}{</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>\sum_i (y_i-\widehat y_{\mathrm{base},i})^2</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>}.</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>A value of 0 means that the model matches the frame mean baseline. A positive value means that the verb specific prediction removes some of the baseline squared error. A negative value means that it does worse than the baseline.</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>The difference</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>\Delta R^2</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>R^2_{\mathrm{factor}}</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>-</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>R^2_{\mathrm{direct}}</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>tests the second hypothesis. Positive values favor compression. Negative values favor the complete distribution.</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>Uncertainty is computed with the <span class="co">[</span><span class="ot">bootstrap</span><span class="co">](../statistical-inference/bootstrap-confidence-intervals.qmd)</span> by resampling verbs. Each sampled verb contributes all of its frames and all five outer predictions. This preserves the paired comparison between representations and respects the verb as the held-out unit.</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evaluate the hypotheses</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>Before this analysis, we decided that the first hypothesis would count as supported only if direct out-of-sample $R^2$ reached at least 0.20, its verb bootstrap interval lay above zero, and $R^2$ was positive in every repetition. We treated the difference between representations as stable if its interval excluded zero or lay completely between $-0.01$ and $0.01$.</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> representation <span class="pp">|</span> out-of-sample $R^2$ <span class="pp">|</span> 95 percent verb interval <span class="pp">|</span></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|</span></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> direct VALEX profile <span class="pp">|</span> 0.246 <span class="pp">|</span> <span class="co">[</span><span class="ot">0.224, 0.266</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 50 component VALEX profile <span class="pp">|</span> 0.239 <span class="pp">|</span> <span class="co">[</span><span class="ot">0.218, 0.259</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> factor minus direct <span class="pp">|</span> -0.0066 <span class="pp">|</span> <span class="co">[</span><span class="ot">-0.0100, -0.0029</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>The direct model meets all three criteria. Its repetition-specific $R^2$ ranges from 0.238 to 0.250, so the result does not depend on one favorable division of the verbs.</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>The factor model does not support the second hypothesis. Inner validation selected 50 components in all 50 outer folds, which is the largest permitted factor rank. Even that representation has an out-of-sample $R^2$ that is 0.0066 lower than the direct profile, and the difference is negative in all five repetitions. The result is small but stable.</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>This is an informative failure of compression. The direct corpus distribution predicts new selectional profiles, but the PCA directions with the most corpus variation do not preserve all of the information useful for that prediction.</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Reasoning check"}</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>Does selecting 50 components show that English clause selection has 50 latent dimensions?</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>No. It shows that 50 was the best candidate rank for this predictor, response, loss, and candidate set. Since it was also the largest candidate, the validation results suggest that additional VALEX directions may remain useful. They do not identify a true number of grammatical dimensions.</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="fu">## Locate the model's success and failure</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>An overall score can hide a theoretically organized error. White and Rawlins observe that direct corpus prediction is especially weak when an object precedes a finite clause. We fixed that comparison before inspecting the new pilot.</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frame family <span class="pp">|</span> number of frames <span class="pp">|</span> direct $R^2$ <span class="pp">|</span> factor $R^2$ <span class="pp">|</span> factor minus direct <span class="pp">|</span></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> finite clause without object <span class="pp">|</span> 5 <span class="pp">|</span> 0.254 <span class="pp">|</span> 0.238 <span class="pp">|</span> -0.0156 <span class="pp">|</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> finite clause with direct object <span class="pp">|</span> 5 <span class="pp">|</span> 0.083 <span class="pp">|</span> 0.084 <span class="pp">|</span> 0.0010 <span class="pp">|</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> finite declarative <span class="pp">|</span> 4 <span class="pp">|</span> 0.212 <span class="pp">|</span> 0.202 <span class="pp">|</span> -0.0105 <span class="pp">|</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> finite interrogative <span class="pp">|</span> 6 <span class="pp">|</span> 0.203 <span class="pp">|</span> 0.192 <span class="pp">|</span> -0.0116 <span class="pp">|</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> eventive infinitive <span class="pp">|</span> 3 <span class="pp">|</span> 0.268 <span class="pp">|</span> 0.264 <span class="pp">|</span> -0.0035 <span class="pp">|</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> stative infinitive <span class="pp">|</span> 3 <span class="pp">|</span> 0.285 <span class="pp">|</span> 0.278 <span class="pp">|</span> -0.0065 <span class="pp">|</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>The object contrast is much larger than the declarative, interrogative, or infinitival contrasts. Direct out-of-sample $R^2$ falls from 0.254 for finite clauses without an object to 0.083 for their matched object frames. At the individual frame level, direct $R^2$ is 0.037 for <span class="in">`NP Ved NP whether S`</span>, 0.061 for <span class="in">`NP Ved NP whichNP S`</span>, and 0.109 for <span class="in">`NP Ved NP that S`</span>. Their counterparts without an object have values of 0.249, 0.290, and 0.270.</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>PCA does not repair this family level failure. Its $R^2$ is only 0.0010 higher for the five object frames and 0.0156 lower for the matched frames without an object. Thus the stable overall loss and the small local gain are compatible: compression discards useful information in the frames that already work, and restores very little where the direct mapping fails.</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>White and Rawlins connect the object pattern to communicativity. A verb such as *persuade* may license a finite clause after an object because the object refers to a recipient of communicated content. Corpus cooccurrence can register the surface sequence without directly representing that semantic relation. The error pattern is consistent with this proposal, though it does not isolate communicativity from animacy, discourse, or errors in automatic corpus analysis.</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="fu">## Read a few held-out predictions</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>The following values average the five held-out predictions for the fixed example verbs. Positive observed values indicate responses above the relevant participant training baselines.</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> verb and frame <span class="pp">|</span> observed <span class="pp">|</span> direct <span class="pp">|</span> factor <span class="pp">|</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *think* with <span class="in">`that S`</span> <span class="pp">|</span> 1.21 <span class="pp">|</span> 1.55 <span class="pp">|</span> 1.58 <span class="pp">|</span></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *persuade* with <span class="in">`NP to VP[+eventive]`</span> <span class="pp">|</span> 1.65 <span class="pp">|</span> 1.59 <span class="pp">|</span> 1.58 <span class="pp">|</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *wonder* with <span class="in">`whether S`</span> <span class="pp">|</span> 2.77 <span class="pp">|</span> 3.95 <span class="pp">|</span> 4.01 <span class="pp">|</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *try* with <span class="in">`to VP[+eventive]`</span> <span class="pp">|</span> 1.44 <span class="pp">|</span> 2.54 <span class="pp">|</span> 2.57 <span class="pp">|</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *promise* with <span class="in">`to VP[+eventive]`</span> <span class="pp">|</span> 1.83 <span class="pp">|</span> 1.13 <span class="pp">|</span> 1.10 <span class="pp">|</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> *persuade* with <span class="in">`NP that S`</span> <span class="pp">|</span> 1.02 <span class="pp">|</span> -0.07 <span class="pp">|</span> -0.07 <span class="pp">|</span></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>The *persuade* infinitive is predicted closely, while its object plus finite clause is missed by more than one normalized unit. The contrast shows why a profile level score and a frame family diagnostic are both needed. The model has learned something about *persuade*, but it has not learned every route by which the verb licenses a content clause.</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>The overprediction for *wonder* and *try* raises a second issue. Ridge predictions are not constrained to the range of observed cell means. More importantly, a large error for a high acceptability cell can coexist with correct ordering elsewhere in the 50 dimensional profile. The squared error score evaluates both ordering and calibration. A different loss would define a different predictive target.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the application establishes</span></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>The analysis supports three conclusions.</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>VALEX complement distributions contain information about the acceptability profiles of verbs excluded from fitting.</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>PCA compression does not improve this mapping. Nested validation consistently retains the largest candidate rank, and the selected factor model performs slightly worse than the direct profile.</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Prediction remains especially weak for an object followed by a finite clause. The error is organized by a theoretically relevant construction rather than spread uniformly across the response matrix.</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>These conclusions are narrower than a claim that selection reduces to frequency. VALEX is a noisy corpus measurement, MegaAcceptability is an aggregate judgment measurement, and ridge regression estimates a predictive association. The remaining object frame error may point to semantic information absent from the corpus frame inventory, but the present comparison does not identify that information.</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a>The live question is thus more specific than whether abstraction matters. Which representation of communicativity, argument structure, or event structure predicts the object plus finite clause contrast without sacrificing the direct distributional signal in the other frames? Answering that question would require a new theoretically specified predictor and a new held-out comparison. It cannot be answered by renaming the present principal components.</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="fu">## Check the reasoning</span></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>What does one row of the VALEX matrix represent?</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Why are VALEX counts converted to within verb proportions?</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>What is the held-out unit, and which linguistic claim makes that unit appropriate?</span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Which quantities must be refitted inside an inner training split?</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>What is held constant between the direct and factor models?</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Why does a selected rank of 50 not identify 50 grammatical categories?</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Which frame family produces the most pronounced direct prediction failure?</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Does a small stable loss for PCA imply that no abstract representation could improve the mapping?</span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>The final question is the main scope check. This analysis rejects one shallow predictive compression, not abstraction in general. A future abstraction must earn its interpretation through theoretically defined inputs, fold safe fitting, and improved prediction on verbs that did not determine it.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>