project:
  type: default
  output-dir: ../docs/decks
  render:
    - index.qmd
    - data-and-probability/index.qmd
    - random-variables-and-distributions/index.qmd
    - statistical-inference/index.qmd
    - linear-regression/index.qmd
    - model-criticism-and-prediction/index.qmd
    - generalized-linear-models/index.qmd
    - mixed-effects-models/index.qmd
    - experimental-design/index.qmd
    - latent-structure/index.qmd
    - factorization/index.qmd
    - missing-data/index.qmd
    - custom-model-design/index.qmd

execute:
  enabled: false

format:
  revealjs:
    html-math-method: katex

resources:
  - shared/bird.svg
  - shared/theme.css
