project:
  type: default
  output-dir: ../docs/decks
  render:
    - index.qmd
    - data-and-probability/index.qmd

execute:
  enabled: false

format:
  revealjs:
    html-math-method: katex

resources:
  - shared/bird.svg
  - shared/theme.css
